export const GET_OPERACION = "GET_OPERACION";
export const GET_OPERACION_ERROR = "GET_OPERACION_ERROR";

export const ADD_OPERACION = "ADD_OPERACION";
export const ADD_OPERACION_ERROR = "ADD_OPERACION_ERROR";

export const DELETE_OPERACION = "DELETE_OPERACION";
export const DELETE_OPERACION_ERROR = "DELETE_OPERACION_ERROR";