export const GET_SOLDIER = "GET_SOLDIER";
export const GET_SOLDIER_ERROR = "GET_SOLDIER_ERROR";

export const ADD_SOLDIER = "ADD_SOLDIER";
export const ADD_SOLDIER_ERROR = "ADD_SOLDIER_ERROR";

export const DELETE_SOLDIER = "DELETE_SOLDIER";
export const DELETE_SOLDIER_ERROR = "DELETE_SOLDIER_ERROR";

