export const GET_UNIDAD = "GET_UNIDAD";
export const GET_UNIDAD_ERROR = "GET_UNIDAD_ERROR";

export const ADD_UNIDAD = "ADD_UNIDAD";
export const ADD_UNIDAD_ERROR = "ADD_UNIDAD_ERROR";

export const ASSIGN_SOLDIER = "ASSIGN_SOLDIER";
export const ASSIGN_SOLDIER_ERROR = "ASSIGN_SOLDIER_ERROR";

export const ASSIGN_VEHICLE = "ASSIGN_VEHICLE";
export const ASSIGN_VEHICLE_ERROR = "ASSIGN_VEHICLE_ERROR";