export const GET_VEHICULO = "GET_VEHICULO";
export const GET_VEHICULO_ERROR = "GET_VEHICULO_ERROR";

export const ADD_VEHICULO = "ADD_SOLDIER";
export const ADD_VEHICULO_ERROR = "ADD_SOLDIER_ERROR";

export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const DELETE_VEHICLE_ERROR = "DELETE_VEHICLE_ERROR";